version: '3.8'
services:
  shoppy-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    ports:
      - "3400:3400"
    restart: always
